/**
 */
package Petri.provider;

import Petri.util.PetriAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PetriItemProviderAdapterFactory extends PetriAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PetriItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.Places} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlacesItemProvider placesItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.Places}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlacesAdapter() {
		if (placesItemProvider == null) {
			placesItemProvider = new PlacesItemProvider(this);
		}

		return placesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.Transitions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitionsItemProvider transitionsItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.Transitions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitionsAdapter() {
		if (transitionsItemProvider == null) {
			transitionsItemProvider = new TransitionsItemProvider(this);
		}

		return transitionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.ArcsPonderesEntrants} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArcsPonderesEntrantsItemProvider arcsPonderesEntrantsItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.ArcsPonderesEntrants}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArcsPonderesEntrantsAdapter() {
		if (arcsPonderesEntrantsItemProvider == null) {
			arcsPonderesEntrantsItemProvider = new ArcsPonderesEntrantsItemProvider(this);
		}

		return arcsPonderesEntrantsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.ArcsPonderesSortants} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArcsPonderesSortantsItemProvider arcsPonderesSortantsItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.ArcsPonderesSortants}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArcsPonderesSortantsAdapter() {
		if (arcsPonderesSortantsItemProvider == null) {
			arcsPonderesSortantsItemProvider = new ArcsPonderesSortantsItemProvider(this);
		}

		return arcsPonderesSortantsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.ReseauPetri} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReseauPetriItemProvider reseauPetriItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.ReseauPetri}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReseauPetriAdapter() {
		if (reseauPetriItemProvider == null) {
			reseauPetriItemProvider = new ReseauPetriItemProvider(this);
		}

		return reseauPetriItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.Composants} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposantsItemProvider composantsItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.Composants}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComposantsAdapter() {
		if (composantsItemProvider == null) {
			composantsItemProvider = new ComposantsItemProvider(this);
		}

		return composantsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.ArcLectureSeule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArcLectureSeuleItemProvider arcLectureSeuleItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.ArcLectureSeule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArcLectureSeuleAdapter() {
		if (arcLectureSeuleItemProvider == null) {
			arcLectureSeuleItemProvider = new ArcLectureSeuleItemProvider(this);
		}

		return arcLectureSeuleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Petri.Temps} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TempsItemProvider tempsItemProvider;

	/**
	 * This creates an adapter for a {@link Petri.Temps}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTempsAdapter() {
		if (tempsItemProvider == null) {
			tempsItemProvider = new TempsItemProvider(this);
		}

		return tempsItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (placesItemProvider != null) placesItemProvider.dispose();
		if (transitionsItemProvider != null) transitionsItemProvider.dispose();
		if (arcsPonderesEntrantsItemProvider != null) arcsPonderesEntrantsItemProvider.dispose();
		if (arcsPonderesSortantsItemProvider != null) arcsPonderesSortantsItemProvider.dispose();
		if (reseauPetriItemProvider != null) reseauPetriItemProvider.dispose();
		if (composantsItemProvider != null) composantsItemProvider.dispose();
		if (arcLectureSeuleItemProvider != null) arcLectureSeuleItemProvider.dispose();
		if (tempsItemProvider != null) tempsItemProvider.dispose();
	}

}
