<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petri" nsURI="http://petri" nsPrefix="petri">
  <eClassifiers xsi:type="ecore:EClass" name="ReseauPetri">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composants" upperBound="-1"
        eType="#//Composant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composant" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jetons" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervalleTemps" eType="#//Temps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcPondere" eSuperTypes="#//Composant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ponderation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcPondereEntrant" eSuperTypes="#//ArcPondere">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcPondereSortant" eSuperTypes="#//ArcPondere">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcLectureSeule" eSuperTypes="#//ArcPondereEntrant"/>
  <eClassifiers xsi:type="ecore:EClass" name="Temps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tempsMinimum" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tempsMaximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
