#

pluginName = fr.n7.petri Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_ReseauPetri_type = Reseau Petri
_UI_Composants_type = Composants
_UI_Place_type = Place
_UI_Transition_type = Transition
_UI_ArcPondede_type = Arc Pondede
_UI_ArcPondereEntrant_type = Arc Pondere Entrant
_UI_ArcPondereSortant_type = Arc Pondere Sortant
_UI_ArcLectureSeule_type = Arc Lecture Seule
_UI_Temps_type = Temps
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_ReseauPetri_elements_feature = Elements
_UI_ReseauPetri_nom_feature = Nom
_UI_Place_jetons_feature = Jetons
_UI_Place_nom_feature = Nom
_UI_Transition_nom_feature = Nom
_UI_Transition_intervalleTemps_feature = Intervalle Temps
_UI_ArcPondede_ponderation_feature = Ponderation
_UI_ArcPondereEntrant_source_feature = Source
_UI_ArcPondereEntrant_destination_feature = Destination
_UI_ArcPondereSortant_source_feature = Source
_UI_ArcPondereSortant_destination_feature = Destination
_UI_Temps_tempsMinimum_feature = Temps Minimum
_UI_Temps_tempsMaximum_feature = Temps Maximum
_UI_Unknown_feature = Unspecified

_UI_ArcPondere_type = Arc Pondere
_UI_ArcPondere_ponderation_feature = Ponderation
